# Generated by Django 5.1.7 on 2025-03-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
