# Generated by Django 5.1.7 on 2025-03-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
