# Generated by Django 5.1.7 on 2025-03-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wallet',
        ),
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
