# Generated by Django 5.1.7 on 2025-03-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_wallet_customuser_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='balance',
            new_name='wallet',
        ),
    ]
