# Generated by Django 5.1.7 on 2025-03-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_balance_customuser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_investments',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_profit',
            field=models.FloatField(default=0),
        ),
    ]
